namespace: monk-wordpress

stack:
  defines: process-group
  runnable-list:
    - monk-wordpress/db
    - monk-wordpress/wordpress
  variables:
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "wpdb"
    mysql_database_password: 
      type: string
      value: "RhgDPXPEnAgxxXYZ"