namespace: wordpress-mysql-nginx
stack:
  defines: process-group
  runnable-list:
    - wordpress-mysql-nginx/db
    - wordpress-mysql-nginx/wordpress
    - wordpress-mysql-nginx/wp-nginx
  variables:
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "wpdb"
    mysql_database_password:
      type: string
      value: "RhgDPXPEnAgxxXYZ"
    wordpress_port: 8088
    server_name: wordpress.burakhan.com
    mysql-image-tag: 5.6.47
