namespace: monk-wordpress-nginx-ssl
stack:
  defines: process-group
  runnable-list:
    - monk-wordpress-nginx-ssl/db
    - monk-wordpress-nginx-ssl/wordpress
    - monk-wordpress-nginx-ssl/nginx
  variables:
    mysql_database_user: "db_user"
    mysql_database_root_password: "RhgDPXPEnAgJ5q5g"
    mysql_database_name: "wpdb"
    mysql_database_password: 
      type: string
      value: "RhgDPXPEnAgxxXYZ"
    server_name: wordpress.burakhan.com
    email: burakhan@burakhan.com